---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helmrepository.yaml
  - ocirepository.yaml
  - helmrelease.yaml
  - dashboard-overview.yaml
  - dashboard-sidecar.yaml
configMapGenerator:
  - name: thanos-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
