apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - secrets.yaml
configMapGenerator:
  - name: kube-manager-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
