apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ocirepository.yaml
  - helmrelease.yaml
  - secrets.yaml
  - virtualservice.yaml
configMapGenerator:
  - name: kube-manager-values
    namespace: flux-system
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
