---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: valkey
resources:
  - namespace.yaml
  - docker-secret.yaml
  - ocirepository.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: valkey-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
