provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    value: "${CLOUDFLARE_API_TOKEN}"

extraArgs:
  - --cloudflare-proxied
  - --txt-owner-id=${ENVIRONMENT}-external-dns

domainFilters:
  - "${DOMAIN}"

sources:
  - istio-virtualservice