apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - podmonitors.yaml
  - istio-monitors.yaml
  - jaeger
  - kiali
  # - loki
  # - alloy
  # - thanos
  # - tempo
  # - opentelemetry-operator
