---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-ingress
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - autorizationpolicy.yaml
configMapGenerator:
  - name: istio-ingress-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
