autoscaling:
  enabled: true
  minReplicas: 2
resources:
  requests:
    cpu: 10m
    memory: 128Mi
service:
  type: "${service:=LoadBalancer}"
  loadBalancerSourceRanges:
  - 91.211.91.3/32  # dev
  - 91.211.91.148/32  # pl
  - 91.211.91.186/32  # ua
  - 2.56.125.90/32  # ocp vpn
  - 46.4.20.147/32  # Vlad
  - 143.47.228.252/32  # Vlad
