apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-configs
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
data:
  PROJECT: "kube-manager"
  ENVIRONMENT: "kube-dev"
  HOST: "k8s-dev.ocplanet.cloud"
  EMAIL_DOMAIN: "info@onecloudplanet.com"
  ISTIO_VERSION: "1.24.2"
  CNPG_BUCKET: "k8s-dev-backup"
  CNPG_ENDPOINTURL: "https://k8s-dev-backup.s3.ua-central-1.ocplanet.cloud"
