---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - virtualservice.yaml
configMapGenerator:
  - name: kiali-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
