apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alertmanager
spec:
  hosts:
    - "alertmanager.${HOST}"
  gateways:
    - istio-ingress/public-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: alertmanager-operated
            port:
              number: 9093
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
spec:
  hosts:
    - "prometheus.${HOST}"
  gateways:
    - istio-ingress/public-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: prometheus-operated
            port:
              number: 9090
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
spec:
  gateways:
    - istio-ingress/public-gateway
  hosts:
    - "grafana.${HOST}"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: prometheus-stack-grafana
            port:
              number: 80
